/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "% chance when breaking any other ore. Using them has a chance of improving your tool. Upgrading your tool will reset the boost.": "%的几率。 使用它们有机会改进您的工具。 升级你的工具将重置提升。",
    "Are you sure you want to ascend?": "您确定要转生吗？",
    "artifacts": "神器",
    "Artifacts have a 100% drop chance when breaking an ore for the first time, or a": "第一次破坏矿石时，神器有 100% 的几率掉落，或者当打破任何其他矿石时，有",
    "Ascend and gain": "转生与增益",
    "ascension points (AP)": "转生点 (AP)",
    "Ascension will reset your tool and upgrades in exchange for AP. Each AP gives a 1% boost to damage.": "提升将重置你的工具并升级以换取AP。 每个 AP 都会使伤害提高 1%。",
    "Back": "返回",
    "Congrats! You have transcended and beaten the game!": "恭喜！ 你已经超越并击败了游戏！",
    "Costs": "成本",
    "Current boost:": "当前转生：",
    "Export game": "导出游戏",
    "Hard reset": "硬重置",
    "Hardness:": "硬度：",
    "Hit points:": "生命值：",
    "However, you can continue playing if you like. Higher levels of transcendence await you...": "但是，如果您愿意，可以继续玩。 更高层次的超越等待着你……",
    "Import game": "导入游戏",
    "Large number formatting:": "大数字格式化：",
    "Level": "等级",
    "Next at": "下一个在",
    "Okay": "好的",
    "On": "开",
    "Ore icons generated using Midjourney": "使用 Midjourney 生成的矿石图标",
    "Ore value": "矿石价值",
    "Original Mine Clicker by Tolan (2014)": "Tolan 原创《采矿点击器》 (2014)",
    "Pickaxe": "镐子",
    "Sand": "沙",
    "Shovel": "铲子",
    "Stats & Info": "统计与信息",
    "Tap an upgrade for info": "点击升级以获取信息",
    "Test message": "测试消息",
    "Time played:": "游玩时间：",
    "Tool": "工具",
    "Top bar messages:": "顶部栏消息：",
    "Total ores mined:": "开采矿石总量：",
    "Unlocks at level 10!": "10级解锁！",
    "Unlocks at level 100!": "100级解锁！",
    "Upgrade to a": "升级到",
    "Upgrades": "升级",
    "Use artifact": "使用神器",
    "You have a": "你有一个",
    "Your artifact boost is currently capped at": "您的神器提升目前上限为",
    "Chalk": "白垩土",
    "Clay": "黏土",
    "Rusty drill": "生锈的钻头",
    "Stone drill": "石头钻头",
    "Value/click": "价值/点击",
    "Stone": "石头",
    "Coal": "煤",
    "Standard long": "标准长",
    "Tin": "锡",
    "Copper": "铜",
    "Copper drill": "铜钻头",
    "Iron drill": "铁钻头",
    "Obsidian drill": "黑曜石钻头",
    "Nickel": "镍",
    "Iron": "铁",
    "Obsidian": "黑曜石",
    "Central layer": "中央层",
    "Shallow layer": "浅层",
    "Increase damage": "增加伤害",
    'Deep layer': '深层',
    "Mantle layer": "地幔层",
    "Core layer": "地核层",
    "Outer space": "外太空",
    "Interstellar space": "星际空间",
    "Intergalactic space": "系外空间",
    "The multiverse": "多重宇宙",
    "Outer reality": "外在显示",
    "Transcendence": "超越",
    'Silver': '银',
    'Gold': '金',
    'Platinum': '铂',
    'Titanium': '钛',
    'Iridium': '铱',
    'Malachite': '孔雀石',
    "Topaz": "黄玉",
    "Lapis lazuli": "青金石",
    "Amethyst": "紫水晶",
    "Opal": "蛋白石",
    "Aquamarine": "海蓝宝石",
    "Sapphire": "蓝宝石",
    "Emerald": "绿宝石",
    "Ruby": "红宝石",
    "Diamond": "钻石",
    "Uranium": "铀",
    "Plutonium": "钚",
    "Mythril": "秘银",
    "Adamantium": "艾德曼合金",
    "Kryptonite": "氪石",
    "Vibranium": "振金",
    "Neutronium": "中子",
    "Unobtanium": "难得素",
    "Dark matter": "暗物质",
    "Quark soup": "夸克汤",
    "Degenerate matter": "简并态物质",
    "Red matter": "红物质",
    "Pentaquark matter": "五夸克物质",
    "Strangelet": "奇异夸克团",
    "Preon matter": "前子",
    "Antimatter": "反物质",
    "Small asteroid": "小行星",
    "Large asteroid": "大型小行星",
    "Platinum asteroid": "铂质小行星",
    "Alien spaceship": "外星飞船",
    "Alien mothership": "外星母舰",
    "Small moon": "小型卫星",
    "Large moon": "大型卫星",
    "Exoplanet": "系外行星",
    "Ecumenopolis": "理想城",
    "Large exoplanet": "巨行星",
    "Brown dwarf": "褐矮星",
    "Main sequence star": "主序星",
    "Hypergiant star": "特超巨星",
    "Nebula": "星云",
    "Black hole": "黑洞",
    "Small galaxy": "小型星系",
    "Galaxy": "星系",
    "Large galaxy": "大型星系",
    "Great void": "大空洞",
    "Galaxy filaments": "星系细丝",
    "Supercluster": "超星系团",
    "Small universe": "小型宇宙",
    "Large universe": "大型宇宙",
    "Light universe": "亮宇宙",
    "Neon universe": "霓虹宇宙",
    "Chaos universe": "混沌宇宙",
    "Gold universe": "黄金宇宙",
    "Power universe": "超能宇宙",
    "Multiverse": "多重宇宙",
    "Kiloverse": "千宇宙",
    "Megaverse": "兆宇宙",
    "Gigaverse": "吉宇宙",
    "Xenoverse": "异种宇宙",
    "Ultraverse": "超级宇宙",
    "Hyperverse": "超越宇宙",
    "Omniverse": "万象宇宙",
    "Steel drill": "钢钻头",
    "Golden drill": "金钻头",
    "Titanium drill": "钛钻头",
    "Emerald drill": "绿宝石钻头",
    "Ruby drill": "红宝石钻头",
    "Diamond drill": "钻石钻头",
    "Mythril drill": "秘银钻头",
    "Adamantium drill": "艾德曼合金钻",
    "Vibranium drill": "振金钻",
    "Unobtanium drill": "难得素钻",
    "Dark matter drill": "暗物质钻",
    "Antimatter drill": "反物质钻",
    "Blue laser drill": "蓝色激光钻",
    "Green laser drill": "绿色激光钻",
    "Red laser drill": "红色激光钻",
    "White laser drill": "白色激光钻",
    "Dark laser drill": "暗黑激光钻",
    "Antilaser drill": "反激光钻",
    'Artifacts': '神器',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "Transcendence": "超越",
    "Devourer ": "吞噬者",
    "Tool upgraded!": "工具升级！",
    "Not strong enough... ": "不够强力...",
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Damage:": "伤害:",
    "Unlocks at level ": "解锁于等级 ",
    "Now entering: ": "现在进入：",
    "Costs $": "成本 $",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+) \-\> ([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);